### ISSUE TITLE
Create a release checklist

### ISSUE THREAD

**Issue by florg-32** [SpaceTeam/STS1_EDU_Scheduler#87]
Create a checklist that can be used before releasing a build for HAF or else.

It should contain stuff like

- [ ] Software tests passed after clean
- [ ] no clippy warnings
- [ ] hardware tests passed
- [ ] profiler stuff checked...

**Comment by florg-32** [comment]
Will be done in milestone
